name: lifora
description: "Smart Wearable Emergency Communication System"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.35.5
  geolocator: ^11.1.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true